#!/usr/bin/env bash
# Bash script to install and configure nginx web server
sudo apt-get update && sudo apt-get install -y nginx
ufw allow 'Nginx HTTP'
echo "Holberton School" > /var/www/html/index.nginx-debian.html
service nginx start
