#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.
sudo apt-get update && sudo apt-get install -y nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
variable="rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sed -i "19i $variable" /etc/nginx/sites-available/default
service nginx restart
