#!/usr/bin/env bash
# 4-if_9_say_hi: displays "Holberton School" 10 times, but for the 9th
#+ iteration, displays "Holberton School" and then "Hi"

i=0
while (( i < 10 )); do
    echo "Holberton School"
    if (( i == 8 )); then
        echo "Hi"
    fi
    (( i++ ))
done