#!/usr/bin/env bash
# 6-superstitious_numbers: displays the numbers from 1 to 10 along with some
#+ other stuff depending on what loop number is occuring

i=1
while (( i <= 20 )); do
    case $i in
        4)  echo "$i"
            echo "bad luck from China"
            ;;
        9) echo "$i"
            echo "bad luck from Japan"
            ;;
        17) echo "$i"
            echo "bad luck from Italy"
            ;;
        *)
            echo "$i"
    esac
    (( i++ ))
done