#!/usr/bin/env bash
#Write a Bash script that configures an Ubuntu server with the below requirements
cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.new
sed -i '1 i\8.8.8.8 facebook.com' ~/hosts.new
cp -f ~/hosts.new /etc/hosts